# Generated by Django 4.0.3 on 2022-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuote',
            name='tuotekuva',
            field=models.ImageField(blank=True, default='default.png', upload_to='tuotekuvat'),
        ),
    ]
