# Generated by Django 4.0.3 on 2022-04-13 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='henkilo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='varastotapahtuma',
            old_name='varastosta',
            new_name='varasto',
        ),
        migrations.RemoveField(
            model_name='varastotapahtuma',
            name='varastoon',
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='maara',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
