# Generated by Django 4.0.3 on 2022-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(blank=True, help_text='Päivä jona tuote tulisi viimeistään palauttaa', null=True, verbose_name='palautuspäivä'),
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='aikaleima',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Lainaus',
        ),
    ]
