# Generated by Django 4.0.3 on 2022-05-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuote',
            name='nimike',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
