# Generated by Django 4.0.3 on 2022-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='henkilo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='henkilo',
            name='salasana',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
