# Generated by Django 4.0.3 on 2022-03-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0002_henkilo_email_henkilo_salasana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='henkilo',
            name='salasana',
        ),
    ]
