# Generated by Django 4.0.3 on 2022-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0002_alter_tuote_nimike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuote',
            name='viivakoodi',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
