# Generated by Django 4.0.3 on 2022-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0002_tuote_kappalemaara_lainassa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuote',
            name='kappalemaara_lainassa',
            field=models.PositiveIntegerField(default=0, verbose_name='kappalemäärä lainassa'),
        ),
    ]
