# Generated by Django 4.0.3 on 2022-05-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0002_varastotapahtuma_palautuspaiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='arkistotunnus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='asiakas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asiakas', to=settings.AUTH_USER_MODEL),
        ),
    ]
