# Generated by Django 4.0.3 on 2022-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0002_alter_henkilo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='henkilo',
            name='rooli',
            field=models.CharField(choices=[('oppilas', 'Oppilas'), ('varastonhoitaja', 'Varastonhoitaja'), ('opettaja', 'Opettaja'), ('hallinto', 'Hallinto')], default='oppilas', max_length=20),
        ),
    ]
