# Generated by Django 4.0.3 on 2022-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0003_alter_henkilo_rooli'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuote',
            name='hankintapaiva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
