# Generated by Django 4.0.3 on 2022-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varastonhallintasovellus', '0003_remove_henkilo_salasana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuoteryhma',
            old_name='ryhman_nimi',
            new_name='nimi',
        ),
        migrations.RenameField(
            model_name='varasto',
            old_name='varaston_nimi',
            new_name='nimi',
        ),
        migrations.RenameField(
            model_name='varasto',
            old_name='varastotyyppi_FK',
            new_name='varastotyyppi',
        ),
        migrations.RenameField(
            model_name='varastotapahtuma',
            old_name='asiakas_FK',
            new_name='asiakas',
        ),
        migrations.RenameField(
            model_name='varastotapahtuma',
            old_name='viivakoodi_FK',
            new_name='tuote',
        ),
        migrations.RenameField(
            model_name='varastotapahtuma',
            old_name='varasto_FK',
            new_name='varasto',
        ),
        migrations.RenameField(
            model_name='varastotapahtuma',
            old_name='varastonhoitaja_FK',
            new_name='varastonhoitaja',
        ),
        migrations.RenameField(
            model_name='varastotyyppi',
            old_name='varastotyypin_nimi',
            new_name='nimi',
        ),
        migrations.RemoveField(
            model_name='henkilo',
            name='roolinimitys_FK',
        ),
        migrations.AddField(
            model_name='henkilo',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='henkilo',
            name='rooli',
            field=models.CharField(choices=[('oppilas', 'Oppilas'), ('opettaja', 'Opettaja')], default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='Rooli',
        ),
    ]
